# Generated by Django 4.2.7 on 2023-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.TextField(default="DefaultBrand"),
            preserve_default=False,
        ),
    ]
