# Generated by Django 4.2.7 on 2023-11-29 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_product_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brand",
            new_name="Availability",
        ),
    ]
