# Generated by Django 4.2 on 2023-12-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_brand_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Default Brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.TextField(default='In Stock', max_length=255),
        ),
    ]
