# Generated by Django 4.2 on 2023-12-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_brand_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.TextField(default='In Stock', max_length=255),
        ),
    ]
