# Generated by Django 4.2 on 2023-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_brand_alter_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BK', 'Books'), ('AR', 'Accessories'), ('MC', 'Merchandise'), ('SI', 'Stationery Items'), ('EC', 'Electronics'), ('MN', 'Men'), ('WM', 'Women')], max_length=2),
        ),
    ]
