# Generated by Django 4.2 on 2023-12-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shirt_size',
        ),
    ]
